version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: algoarena
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/db/init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: initialization script
    ports:
      - "5432:5432"
    networks:
      - app-network

  # API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://admin:pass1234@db:5432/algoarena
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./packages/db/prisma:/app/packages/db/prisma # For migrations
      - ./apps/backend:/app/apps/backend # For migrations

  # Web Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://admin:pass1234@db:5432/algoarena
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db
    networks:
      - app-network

  # Migration runner (runs once and exits)
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      DATABASE_URL: postgresql://admin:pass1234@db:5432/algoarena
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./packages/db/prisma:/app/packages/db/prisma
    command:
      [
        "npx",
        "prisma",
        "migrate",
        "deploy",
        "--schema=./packages/db/prisma/schema.prisma",
      ]
    restart: "no"

  studio:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      DATABASE_URL: postgresql://admin:pass1234@db:5432/algoarena
    depends_on:
      - db
      - migrate
    networks:
      - app-network
    ports:
      - "5555:5555"
    volumes:
      - ./packages/db/prisma:/app/packages/db/prisma
    command:
      ["npx", "prisma", "studio", "--schema=./packages/db/prisma/schema.prisma"]
    restart: "no"
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
